FirstASPNETWebApp/FirstASPNETWebApp/Models/FanMailModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FirstASPNETWebApp.Models
{
    public class FanMailModel
    {
        [Required] //// validation
        public string From { get; set; }
        public string Subject { get; set; }
        [Required]
        [MaxLength(25)]
        public string Message { get; set; }
    }
}

FirstASPNETWebApp/FirstASPNETWebApp/Controllers/BlahController.cs
using FirstASPNETWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FirstASPNETWebApp.Controllers
{
    public class BlahController : Controller // inherits from general controller class
    {
        public IActionResult Index() // index action, with particular view (default is the name at top : Index())
        {
            return View();
        }

        [HttpGet] // attribute attached to our method to distinguish the two types, differentiating between the two
        public IActionResult FanMail()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FanMail(FanMailModel model)
        {
            return View();
        }
    }
}

FirstASPNETWebApp/FirstASPNETWebApp/Views/Blah/FanMail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model FanMailModel;

<h2>Send Him Fan Mail</h2>
<form method="post">
    <label>From:</label>
    <input id="txtFrom" asp-for="From" /><br />
    <label>Subject:</label>
    <input id="txtSubject" asp-for="Subject" /><br />
    <label>Message:</label>
    <textarea id="txtMessage" asp-for="Message" rows="4"></textarea><br />
    <input id="btnSend" type="submit" value="Send Message" />

    <!--add this summary to report to user if their form was filled out correctly-->
    <div asp-validation-summary="All"></div>
</form>

<script src="js/FanMail.js"></script>

FirstASPNETWebApp/FirstASPNETWebApp/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Prof Ganderson Fan Club";
}

<!--combining our c# code with html in razor code-->

<h1>Prof. Ganderson Fan Site</h1>
<img id="picGanderson" src="img/ganderson.jpg" />
<p>Prof. Anderson (a.k.a. "Prof Ganderson") is a Professor in the Information Systems department at BYU</p>

<p>Pop Quiz: We love him because:</p>
<ul>
    <li>A: The flowing locks he had when he was younger</li>
    <li>B: He can pound a pound of bacon</li>
    <li>C: His exams are so easy!</li>
    <li>D: He is just an awesome person who cares about everybody around him</li>
    <li>E: All of the above</li>
</ul>

FirstASPNETWebApp/FirstASPNETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="lib/bootstrap/bootstrap-5.3.0-alpha1-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/default.css" rel="stylesheet" />
</head>

<body>

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="FanMail">Fan Mail</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <footer>This is the footer</footer>

    <script src="lib/bootstrap/bootstrap-5.3.0-alpha1-dist/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.3.min.js"></script>

</body>
</html>